import {
  AttachmentManager,
  AttachmentManagerAttributes,
} from "src/exports/attachment-manager.js";
import { LOADING_STATES } from "src/exports/elements/attachment-editor.js";
import type { LoadingState } from "src/exports/elements/attachment-editor.js";
import { mergeAttributes, Node } from "@tiptap/core";
import { selectionToInsertionEnd } from "src/internal/selection-to-insertion-end.js";
import { Maybe } from "src/types";
import { findAttribute } from "./find-attribute";
import { toDefaultCaption } from "src/internal/to-default-caption";
import { fileUploadErrorMessage } from "../translations";
import { Plugin, PluginKey } from "@tiptap/pm/state";
import { findChildrenByType } from "prosemirror-utils";
import { AttachmentRemoveEvent } from "../events/attachment-remove-event";

import { render, html } from "lit/html.js";
import { unsafeHTML } from "lit/directives/unsafe-html.js";
import { ifDefined } from "lit/directives/if-defined.js";
import { when } from "lit/directives/when.js";

interface AttachmentAttrs extends AttachmentManagerAttributes {
  loadingState: LoadingState;
  previewable: boolean;
  progress: number;

  // Image
  width?: Maybe<number>;
  height?: Maybe<number>;

  [key: string]: unknown;
}

export interface AttachmentOptions {
  HTMLAttributes: Record<string, any>;
  fileUploadErrorMessage: string;
}

declare module "@tiptap/core" {
  interface Commands<ReturnType> {
    attachment: {
      /**
       * Add an attachment(s)
       */
      setAttachment: (
        options: AttachmentManager | AttachmentManager[],
      ) => ReturnType;
    };
  }
}

/** https://github.com/basecamp/trix/blob/main/src/trix/models/attachment.coffee#L4 */
const isPreviewable = /^image(\/(gif|png|jpe?g)|$)/;

function canPreview(previewable: Boolean, contentType: Maybe<string>): Boolean {
  return previewable || contentType?.match(isPreviewable) != null;
}

function toExtension(fileName: Maybe<string>): string {
  if (!fileName) return "";

  return "attachment--" + fileName.match(/\.(\w+)$/)?.[1].toLowerCase();
}

function toType(content: Maybe<string>, previewable: Boolean): string {
  if (previewable) {
    return "attachment--preview";
  }

  if (content) {
    return "attachment--content";
  }

  return "attachment--file";
}

export const Attachment = Node.create<AttachmentOptions>({
  name: "attachment-figure",
  group: "block attachmentFigure",
  content: "inline*",
  selectable: true,
  draggable: true,
  isolating: true,
  defining: true,

  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey("rhino-attachment-remove-event"),
        view() {
          return {
            update(view, prevState) {
              const nodeType = view.state.schema.nodes["attachment-figure"];

              const attachmentNodesBefore = findChildrenByType(
                prevState.doc,
                nodeType,
              );

              type FindNodeResult = ReturnType<typeof findChildrenByType>;
              type FindNodeResultObj = FindNodeResult[keyof FindNodeResult];

              const afterSgidsAndAttachmentIds = new Map<
                string,
                FindNodeResultObj
              >();

              // attachmentNodesAfter state transform
              findChildrenByType(view.state.doc, nodeType).forEach((node) => {
                const nodeAttrs = node.node
                  .attrs as AttachmentManagerAttributes;
                const key = nodeAttrs.sgid || nodeAttrs.attachmentId;

                if (key) {
                  afterSgidsAndAttachmentIds.set(key, node);
                }
              });

              attachmentNodesBefore.forEach((node) => {
                const nodeAttrs = node.node
                  .attrs as AttachmentManagerAttributes;

                const key = nodeAttrs.sgid || nodeAttrs.attachmentId;

                if (!key) return;
                if (afterSgidsAndAttachmentIds.has(key)) return;

                const attachmentManager = new AttachmentManager(
                  nodeAttrs,
                  view,
                );
                view.dom.dispatchEvent(
                  new AttachmentRemoveEvent(attachmentManager),
                );
              });
            },
          };
        },
      }),
    ];
  },
  addOptions() {
    return {
      HTMLAttributes: {
        class: "attachment",
        "data-trix-attributes": JSON.stringify({ presentation: "gallery" }),
      },
      fileUploadErrorMessage: fileUploadErrorMessage,
    };
  },

  parseHTML() {
    return [
      // Generated by #to_trix_html
      {
        tag: "figure[data-trix-attachment]",
        // contentElement: "figcaption"
      },
      // Generated by the standard output.
      {
        tag: "figure.attachment",
        contentElement: "figcaption",
      },
    ];
  },

  renderHTML({ node }) {
    const {
      // Figure
      content,
      contentType,
      sgid,
      fileName,
      fileSize,
      caption,
      url,
      previewable,

      // Image
      src,
      width,
      height,
    } = node.attrs as AttachmentAttrs;

    const attachmentAttrs = {
      caption,
      contentType,
      content,
      filename: fileName,
      filesize: fileSize,
      height,
      width,
      sgid,
      url,
      src,
    };

    const figure = [
      "figure",
      mergeAttributes(this.options.HTMLAttributes, {
        class:
          this.options.HTMLAttributes.class +
          " " +
          toType(content, canPreview(previewable, contentType)) +
          " " +
          toExtension(fileName),
        "data-trix-content-type": contentType,
        "data-trix-attachment": JSON.stringify(attachmentAttrs),
        "data-trix-attributes": JSON.stringify({
          caption,
          presentation: "gallery",
        }),
      }),
    ] as const;

    const figcaption = [
      "figcaption",
      mergeAttributes(
        {},
        { class: "attachment__caption attachment__caption--edited" },
      ),
      0,
    ] as const;

    const image = [
      "img",
      mergeAttributes(
        {},
        {
          src: url || src,
          contenteditable: false,
          width,
          height,
        },
      ),
    ];

    if (!content) {
      return [...figure, image, figcaption];
    }

    return [...figure, figcaption];
  },

  addAttributes() {
    return {
      attachmentId: { default: null },
      caption: {
        default: "",
        parseHTML: (element) => {
          return (
            element.querySelector("figcaption")?.innerHTML ||
            findAttribute(element, "caption")
          );
        },
      },
      progress: {
        default: 0,
        parseHTML: (element) => (findAttribute(element, "sgid") ? 100 : 0),
      },
      loadingState: {
        default: LOADING_STATES.notStarted,
        parseHTML: (element) =>
          findAttribute(element, "sgid")
            ? LOADING_STATES.success
            : LOADING_STATES.notStarted,
      },
      sgid: {
        default: "",
        parseHTML: (element) => findAttribute(element, "sgid"),
      },
      src: {
        default: "",
        parseHTML: (element) => findAttribute(element, "src"),
      },
      height: {
        default: "",
        parseHTML: (element) => findAttribute(element, "height"),
      },
      width: {
        default: "",
        parseHTML: (element) => {
          return findAttribute(element, "width");
        },
      },
      contentType: {
        default: "",
        parseHTML: (element) => {
          // This is a special case where it exists as:
          // figure["data-trix-attachment"]["contentType"] and
          // action-text-attachment["content-type"]
          return (
            findAttribute(element, "content-type") ||
            JSON.parse(element.getAttribute("data-trix-attachment") || "")
              .contentType ||
            "application/octet-stream"
          );
        },
      },
      fileName: {
        default: "",
        parseHTML: (element) => findAttribute(element, "filename"),
      },
      fileSize: {
        default: "",
        parseHTML: (element) => findAttribute(element, "filesize"),
      },
      content: {
        default: "",
        parseHTML: (element) => {
          return (
            findAttribute(element, "content") ||
            element.closest("action-text-attachment")?.innerHTML ||
            ""
          );
        },
      },
      url: {
        default: "",
        parseHTML: (element) => {
          return findAttribute(element, "url");
        },
      },
      previewable: {
        default: false,
        parseHTML: (element) => {
          const { previewable } = JSON.parse(
            element.getAttribute("data-trix-attachment") || "{}",
          );

          return previewable;
        },
      },
    };
  },

  addNodeView() {
    return ({ node, getPos, editor }) => {
      const {
        content,
        contentType,
        sgid,
        fileName,
        progress,
        fileSize,
        url,
        src,
        width,
        height,
        caption,
        previewable,
        loadingState,
      } = node.attrs as AttachmentAttrs;

      const trixAttachment = JSON.stringify({
        contentType,
        content,
        filename: fileName,
        filesize: fileSize,
        height,
        width,
        sgid,
        url,
        caption,
      });

      const trixAttributes = JSON.stringify({
        presentation: "gallery",
        caption,
      });

      const figureClasses = `
        ${this.options.HTMLAttributes.class}
        ${toType(content, canPreview(previewable, contentType))}
        ${toExtension(fileName)}
      `;

      const scratch = document.createElement("div");

      function handleFigureClick(e: Event) {
        const target = e.currentTarget as HTMLElement;
        const figcaption = target.querySelector("figcaption");

        if (figcaption == null) return;

        if (e.composedPath().includes(figcaption)) {
          return;
        }

        if (typeof getPos === "function") {
          editor
            .chain()
            .setTextSelection(getPos() + 1)
            .run();
        }
      }

      // const img = document.createElement("img");
      // img.setAttribute("contenteditable", "false");
      // img.setAttribute("width", String(width));
      // img.setAttribute("height", String(height));

      // Clean up any objects laying around
      if (url) {
        try {
          URL.revokeObjectURL(src);
        } catch (_e) {}
      }

      const isPreviewable = canPreview(previewable, contentType);

      let imgSrc: string | undefined = undefined;

      if (isPreviewable && (url || src)) {
        imgSrc = url || src;
      }

      function handleImageLoad(e: Event) {
        if (!isPreviewable) return;

        if (!width || !height) {
          const { naturalHeight: height, naturalWidth: width } =
            e.currentTarget as HTMLImageElement;

          if (typeof getPos === "function") {
            const view = editor.view;
            view.dispatch(
              view.state.tr.setNodeMarkup(getPos(), undefined, {
                ...node.attrs,
                height: height,
                width: width,
              }),
            );
          }
        }
      }

      const template = html`
        <figure
          class=${figureClasses}
          sgid=${ifDefined(sgid ? sgid : undefined)}
          data-trix-content-type=${contentType}
          data-trix-attachment=${trixAttachment}
          data-trix-attributes=${trixAttributes}
          @click=${handleFigureClick}
        >
          <rhino-attachment-editor
            file-name=${fileName || ""}
            file-size=${String(fileSize || 0)}
            contenteditable="false"
            loading-state=${loadingState || LOADING_STATES.notStarted}
            progress=${progress}
          >
          </rhino-attachment-editor>

          ${when(
            content && !isPreviewable,
            /* This is really not great. This is how Trix does it, but it feels very unsafe.
               https://github.com/basecamp/trix/blob/fda14c5ae88a0821cf8999a53dcb3572b4172cf0/src/trix/views/attachment_view.js#L36
            */
            () => html`${unsafeHTML(content)}`,
            () => html`
              <img
                class=${loadingState === LOADING_STATES.error
                  ? "rhino-upload-error"
                  : ""}
                contenteditable="false"
                width=${String(width)}
                height=${String(height)}
                src=${ifDefined(imgSrc)}
                @load=${handleImageLoad}
              />
            `,
          )}

          <figcaption
            class=${`attachment__caption ${caption ? "" : "is-empty"}`}
            data-placeholder="Add a caption..."
            data-default-caption=${toDefaultCaption({ fileName, fileSize })}
            progress=${String(progress)}
            .fileUploadErrorMessage=${this.options.fileUploadErrorMessage}
          ></figcaption>
        </figure>
      `;
      render(template, scratch);

      const dom = scratch.firstElementChild;
      const contentDOM = dom?.querySelector("figcaption");

      return {
        dom,
        contentDOM,
      };
    };
  },

  addCommands() {
    return {
      setAttachment:
        (options: AttachmentManager | AttachmentManager[]) =>
        ({ state, tr, dispatch }) => {
          const { schema } = state;

          // Attachments disabled, dont pass go.
          const hasGalleriesDisabled =
            schema.nodes["attachment-gallery"] == null;

          const currentSelection = state.doc.resolve(state.selection.anchor);
          const before =
            state.selection.anchor - 2 < 0 ? 0 : state.selection.anchor - 2;
          const nodeBefore = state.doc.resolve(before);

          // If we're in a paragraph directly following a gallery.
          const isInGalleryCurrent =
            currentSelection.node(1).type.name === "attachment-gallery";
          const isInGalleryAfter =
            nodeBefore.node(1)?.type.name === "attachment-gallery";

          const isInGallery = isInGalleryCurrent || isInGalleryAfter;

          const attachments: AttachmentManager[] = Array.isArray(options)
            ? options
            : ([] as AttachmentManager[]).concat(options);

          let attachmentNodes = attachments.map((attachment) => {
            return schema.nodes["attachment-figure"].create(
              attachment,
              attachment.caption ? [schema.text(attachment.caption)] : [],
            );
          });

          const end = currentSelection.end();

          if (hasGalleriesDisabled) {
            attachmentNodes = attachmentNodes.flatMap((node) => [
              node,
              schema.nodes.paragraph.create(),
            ]);
            tr.insert(end, attachmentNodes);

            if (dispatch) dispatch(tr);
            return true;
          }

          if (isInGallery) {
            const backtrack = isInGalleryCurrent ? 0 : 2;
            tr.insert(end - backtrack, attachmentNodes);
          } else {
            const currSelection = state.selection;

            const gallery = schema.nodes["attachment-gallery"].create(
              {},
              attachmentNodes,
            );

            tr.replaceWith(currSelection.from - 1, currSelection.to, [
              schema.nodes.paragraph.create(),
              gallery,
              schema.nodes.paragraph.create(),
            ]);

            selectionToInsertionEnd(tr, tr.steps.length - 1, -1);
          }

          if (dispatch) dispatch(tr);
          return true;
        },
    };
  },
});
