#!/usr/bin/env ruby -i

# https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset
require "json"
json = `gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  --hostname HOSTNAME \
  /repos/OWNER/REPO/releases/RELEASE_ID/assets?name=example.zip
`
puts json
